title: DNX One
email: contact@dnx.solutions
description: >- # this means to ignore newlines until "baseurl:"
  At DNX we help your business build better solutions by upgrading how
  delivery is done, leaving behind manual processes and embracing an
  automated, cloud-native way of working.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://docs.dnx.one" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed

# just-the-docs Config
color_scheme: default

heading_anchors: true
logo: "/assets/images/logo.png"

# Footer content
# appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 DNX Solutions. Distributed by an <a href=\"https://github.com/dnxlabs/docs.dnx.one/tree/master/LICENSE.txt\">Apache-2.0 LICENSE.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/dnxlabs/docs.dnx.one" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
